# Generated by Django 4.2.5 on 2023-09-18 05:14

from django.db import migrations

def create_data(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Task(first_name="Joe", last_name="Silver", email="joe@email.com", document="22342342", phone="00000000", photo='media/photo/nophoto.png').save()
    Task(first_name="John", last_name="Smith", email="john@email.com", document="11111111", phone="11111111", photo='media/photo/nophoto.png').save()
    Task(first_name="Alex", last_name="Smth", email="alex@email.com", document="22222222", phone="22222222", photo='media/photo/nophoto.png').save()
    Task(first_name="Kira", last_name="Night", email="kira@email.com", document="33333333", phone="33333333", photo='media/photo/nophoto.png').save()
    Task(first_name="Amanda", last_name="Lex", email="amanda@email.com", document="44444444", phone="44444444", photo='media/photo/nophoto.png').save()
    Task(first_name="Oni", last_name="Musha", email="oni@email.com", document="44444444", phone="44444444", photo='media/photo/nophoto.png').save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
